# Generated by Django 5.1.6 on 2025-03-17 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0003_delete_usermanager_user_groups_user_is_superuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_permissions',
        ),
    ]
