version: '3.9'

services:
  web:
    build: .
    container_name: django_web
    command: gunicorn Foodiepro.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:14
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: Foodiepro_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Kiran@84
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
